### ISSUE TITLE
Cannot set property 'prefix' of undefined

### ISSUE THREAD

**Issue by vhpoet** [interledgerjs/ilp-plugin-settlement-adapter#3]
Here's what I get when I'm trying to add the plugin.

```
const plugin = new SettlementPlugin({
        amount,
        currency,
        destination
})

yield connector.instance.addPlugin(pluginName, plugin)
yield connector.instance.getPlugin(pluginName).receive()
yield connector.instance.removePlugin(pluginName)
```

```
2017-01-26T01:43:18.511Z error-handler ERROR TypeError: Cannot set property 'prefix' of undefined
[api]     at Ledgers.add (/Users/vh/localhost/ripple/ilp-kit/node_modules/ilp-connector/src/lib/ledgers.js:80:26)
[api]     at /Users/vh/localhost/ripple/ilp-kit/node_modules/ilp-connector/src/app.js:47:13
[api]     at next (native)
[api]     at onFulfilled (/Users/vh/localhost/ripple/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /Users/vh/localhost/ripple/ilp-kit/node_modules/co/index.js:54:5
[api]     at co (/Users/vh/localhost/ripple/ilp-kit/node_modules/co/index.js:50:10)
[api]     at Object.addPlugin (/Users/vh/localhost/ripple/ilp-kit/node_modules/ilp-connector/src/app.js:45:10)
[api]     at apply (/Users/vh/localhost/ripple/ilp-kit/node_modules/lodash/lodash.js:499:17)
[api]     at Object.wrapper [as addPlugin] (/Users/vh/localhost/ripple/ilp-kit/node_modules/lodash/lodash.js:5356:16)
[api]     at Object.postResource (/Users/vh/localhost/ripple/ilp-kit/api/src/controllers/settlements.js:63:32)
[api]     at next (native)
[api]     at Model.onFulfilled (/Users/vh/localhost/ripple/ilp-kit/node_modules/koa.io/node_modules/co/index.js:61:19)
[api]     at Model.tryCatcher (/Users/vh/localhost/ripple/ilp-kit/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
[api]     at Promise._settlePromiseFromHandler (/Users/vh/localhost/ripple/ilp-kit/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:510:31)
[api]     at Promise._settlePromise (/Users/vh/localhost/ripple/ilp-kit/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:567:18)
[api]     at Promise._settlePromise0 (/Users/vh/localhost/ripple/ilp-kit/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:612:10)
[api]     at Promise._settlePromises (/Users/vh/localhost/ripple/ilp-kit/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:691:18)
[api]     at Async._drainQueue (/Users/vh/localhost/ripple/ilp-kit/node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
[api]     at Async._drainQueues (/Users/vh/localhost/ripple/ilp-kit/node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
[api]     at Immediate.Async.drainQueues (/Users/vh/localhost/ripple/ilp-kit/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
[api]     at runCallback (timers.js:637:20)
[api]     at tryOnImmediate (timers.js:610:5)
[api]     at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by sharafian** [comment]
The settlement adapter has synchronous `getInfo` and `getAccount`, which is only supported in connector versions >13

**Comment by vhpoet** [comment]
I updated the ilp-connector, but still get the same exception.

**Comment by vhpoet** [comment]
Here's the value of `creds` at the time when `creds.options.prefix = ledgerPrefix` is called, it's missing the `options` object.

```
PluginSettlementAdapter {
[api]   _events: { maxListeners: 10 },
[api]   newListener: false,
[api]   verboseMemoryLeak: false,
[api]   _amount: '10.00',
[api]   _currency: 'USD',
[api]   _destination: 'peer.327le.usd.',
[api]   _info:
[api]    { prefix: 'local.settle.f2792bcf-7230-48b7-897d-2348b8c483d0.',
[api]      precision: 4,
[api]      scale: 2,
[api]      currencyCode: 'USD',
[api]      currencySymbol: 'USD' },
[api]   _plugin:
[api]    EventEmitter {
[api]      _events:
[api]       { maxListeners: 10,
[api]         incoming_transfer: [Function],
[api]         incoming_prepare: [Function],
[api]         incoming_fulfill: [Function],
[api]         incoming_cancel: [Function],
[api]         incoming_reject: [Function],
[api]         outgoing_transfer: [Function],
[api]         outgoing_prepare: [Function],
[api]         outgoing_fulfill: [Function],
[api]         outgoing_cancel: [Function],
[api]         outgoing_reject: [Function],
[api]         incoming_message: [Object] },
[api]      newListener: false,
[api]      verboseMemoryLeak: false,
[api]      sendMessage: [Function],
[api]      getInfo: [Function] },
[api]   _client:
[api]    Client {
[api]      _events: { maxListeners: 10 },
[api]      newListener: false,
[api]      verboseMemoryLeak: false,
[api]      connectors: undefined,
[api]      messageTimeout: 10000,
[api]      pendingMessages: {},
[api]      plugin:
[api]       EventEmitter {
[api]         _events: [Object],
[api]         newListener: false,
[api]         verboseMemoryLeak: false,
[api]         sendMessage: [Function],
[api]         getInfo: [Function] },
[api]      connecting: false,
[api]      _extensions: {} },
[api]   _connected: false,
[api]   prefix: 'settlement' }
```

**Comment by sharafian** [comment]
in the plugin's `_info`, the prefix is `'local.settle.f2792bcf-7230-48b7-897d-2348b8c483d0.'` (this is generated by the plugin, and returned by getInfo), but I also see `prefix: 'settlement'`. What prefix are you using to refer to this plugin in the connector? I might have to change the constructor parameters to take a prefix, if you want to specify the prefix manually
